### ISSUE TITLE
evaluate mscoco

### ISSUE THREAD

**Issue by Wong-P** [d-ailin/CLIP-Guided-Decoding#3]
The work is interesting!

Could you please provide 500 mscoco datasets randomly selected during your experiment?

**Comment by d-ailin** [comment]
Sure, please access the ids provided in https://drive.google.com/drive/folders/1r-zZPRRJSv6yoHBzpElGMB3fyALSwNpa?usp=sharing. The json files contains generated responses (with top-k sampling here) with different random seeds. The mscoco id is "image_id" for each item in the json file.

**Comment by Wong-P** [comment]
Thanks！
