### ISSUE TITLE
How to calculate the chair score on nocaps dataset?

### ISSUE THREAD

**Issue by TianyunYoung** [d-ailin/CLIP-Guided-Decoding#5]
I notice that when calculating the chair score on nocaps dataset, the code in nocaps_util.py uses a json named "openimages_hierachy.json". How could I get this json file? Thank you very much.

**Comment by d-ailin** [comment]
Hi, thanks for your interest.

For nocaps chair score computation, this file is actually just an intermediate step and later used to produces JSON files like data/nocaps_corse_classlabels_lower.json. These files will be finally used in the calculating the chair score on nocaps dataset. The openimages_hierachy.json won't be used directly in the execution for evaluation, and I have also uploaded it at https://github.com/d-ailin/CLIP-Guided-Decoding/blob/main/data/openimages_hierachy.json if you need it.

**Comment by TianyunYoung** [comment]
I got it. Thank you very much!
